# Generated by Django 4.2 on 2025-04-02 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0003_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryversion',
            name='stock_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stockmovement'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='is_warehouse_initiated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='rejected_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL),
        ),
    ]
