# Generated by Django 4.2 on 2025-04-02 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventoryversion_stock_movement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocktransfer',
            old_name='rejected_reason',
            new_name='rejection_reason',
        ),
    ]
