# Generated by Django 4.2 on 2025-03-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='email_status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='sms_status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
